name: tw
services:
  twitter-api:
    container_name: twitter-api
    image: tw-api:1.0
    ports:
      - '8080:5000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
